name: Set up GCP
runs:
  using: composite
  steps:
    - id: gcp-auth
      name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
        project_id: ${{ inputs.projectId }}

    - id: gcloud-setup
      name: Setup CLI
      uses: google-github-actions/setup-gcloud@v1

    - id: gcloud-info
      name: Print CLI info
      run: gcloud info