name: Create Terraform stack state bucket
on:
  workflow_dispatch:
        inputs:
            projectId:
                required: true
                type: string
                description: The GCP project id
            region:
                required: true
                type: string
                description: The GCP region where the bucket is created
            bucketSuffix:
                required: true
                type: string
                description: The string to append to the bucket name, in addition to the project id
            saName:
                required: true
                type: string
                description: The name of the service account to attach to the bucket

jobs:
    create-bucket:
        name: Create GS bucket
        runs-on: ubuntu-latest
        steps:
            - id: gcp-auth
              name: Authenticate with GCP
              uses: google-github-actions/auth@v1
              with:
                credentials_json: ${{ secrets.GCP_CREDENTIALS }}
                project_id: ${{ inputs.projectId }}

            - id: gcloud-setup
              name: Setup CLI
              uses: google-github-actions/setup-gcloud@v1

            - id: gcloud-create-bucket
              name: Create bucket in GCP
              run: >
                gcloud storage buckets create gs://${{ inputs.projectId }}-${{ inputs.bucketSuffix }}
                --location=${{ inputs.region }}
                --uniform-bucket-level-access

            - id: output-summary
              name: Output bucket name to summary
              run: |-
                echo "## Bucket name" >> $GITHUB_STEP_SUMMARY
                echo 'A new bucket was created in the `${{ inputs.region }}` region, with the name:' >> $GITHUB_STEP_SUMMARY
                echo '```' >> $GITHUB_STEP_SUMMARY
                echo 'gs://${{ inputs.projectId }}-${{ inputs.bucketSuffix }}' >> $GITHUB_STEP_SUMMARY
                echo '```' >> $GITHUB_STEP_SUMMARY

            - id: attach-bucket-to-sa
              name: Allow bucket access to service account
              run: >
                gsutil iam ch
                serviceAccount:${{ inputs.saName }}@${{ inputs.projectId }}.iam.gserviceaccount.com:objectAdmin
                gs://${{ inputs.projectId }}-${{ inputs.bucketSuffix }}